import streamlit as st

from utils.medgemma_report import (
    ScreeningResults,
    generate_clinical_report,
)


st.set_page_config(page_title="MedGemma Retinal Screening", layout="wide")
st.title("MedGemma Multi-Pathology Retinal Screening")
st.caption("Glaucoma + DR Grading + Vascular Analysis -> Structured Clinical Report")


with st.sidebar:
    st.header("LLM Config")
    use_medgemma = st.toggle("Use MedGemma", value=True)
    model_id = st.text_input("Model ID", value="google/medgemma-4b-it")
    st.markdown("---")
    st.caption("If MedGemma fails to load, the app falls back to a deterministic rule-based report.")


st.subheader("Screening Inputs")
col1, col2, col3 = st.columns(3)

with col1:
    cdr = st.slider("CDR (Glaucoma)", min_value=0.1, max_value=1.0, value=0.55, step=0.001)
    glaucoma_risk = st.selectbox("Glaucoma Risk", ["low", "moderate", "high", "emergent"], index=1)

with col2:
    dr_grade = st.selectbox("DR Grade", [0, 1, 2, 3, 4], index=1)
    dr_label_map = {
        0: "No DR",
        1: "Mild",
        2: "Moderate",
        3: "Severe",
        4: "Proliferative",
    }
    dr_label = dr_label_map[dr_grade]
    dr_conf = st.slider("DR Confidence", min_value=0.0, max_value=1.0, value=0.90, step=0.01)

with col3:
    vessel_density = st.slider("Vessel Density", min_value=0.01, max_value=0.60, value=0.12, step=0.001)


if st.button("Generate Clinical Report", type="primary"):
    results = ScreeningResults(
        cdr=cdr,
        glaucoma_risk=glaucoma_risk,
        dr_grade=int(dr_grade),
        dr_label=dr_label,
        dr_conf=float(dr_conf),
        vessel_density=float(vessel_density),
    )
    output = generate_clinical_report(
        results=results,
        use_medgemma=use_medgemma,
        model_id=model_id,
    )

    mode = output.get("mode", "unknown")
    if mode == "medgemma":
        st.success("Report generated by MedGemma.")
    elif mode == "fallback_rule_based":
        st.warning("MedGemma unavailable. Using rule-based fallback.")
    else:
        st.info("Using rule-based report.")

    if output.get("error"):
        st.code(output["error"], language="text")

    st.subheader("Clinical Report")
    st.markdown(output["report"])

    with st.expander("Prompt Sent to MedGemma"):
        st.code(output["prompt"], language="text")

st.markdown("---")
st.write("Tip: plug this app into your model inference pipeline so these fields are auto-filled from checkpoints.")
